version: "3.1"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-script:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=passme
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=passme --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      mysql:
        condition: service_healthy
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
